### PR TITLE
Build on PHP 7 & codestyle improvements

### PR DESCRIPTION
**Pull request by OndraM**
Hi, thanks for the library!

I've made some minor improvements & cleanups, and enabled build on current PHP versions.

### CODE REVIEW

**Comment by OndraM** [comment]
@rowanhill Hi, what do you think about the PR? Is there anything I can improve to get it merged :)?

**Comment by rowanhill** [comment]
Hi @OndraM - I'm really sorry, I somehow missed this PR, thanks for nudging me!

I haven't touched this project in quite some time (as you may have noticed!), but all of this looks pretty great, I'm happy to merge it in.

Are you actually making use of wiremock-php, then? It's nice to know someone out there is finding it useful, if so :)

**Comment by OndraM** [comment]
@rowanhill Thanks for merging it! May I also ask for tagging a new version?

I so far tried the library a bit and liked it, so we will probably use it in our integration tests :).

**Comment by rowanhill** [comment]
Sure - I've just tagged 1.43.2 for you. Enjoy!

**Pull request merged**
